/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;
/* Header for class com_ntu_zc_eyetracking_NativeClass */

#ifndef _Included_com_ntu_zc_eyetracking_NativeClass
#define _Included_com_ntu_zc_eyetracking_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ntu_zc_eyetracking_NativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
int toGray(Mat img, Mat& gray);
JNIEXPORT jint JNICALL Java_com_ntu_zc_eyetracking_NativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
